services:
  gateway:
    image: nginx:alpine
    ports:
      - "${PORT}:80"
    environment:
      PORT: ${PORT}
    volumes:
      - ./nginx.conf:/etc/nginx/templates/nginx.conf.template
      - /dev/null:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
      - lsp-server

  web:
    build:
      context: ./web-app
      args:
        ODOO_URL: ${ODOO_URL}
    restart: unless-stopped
    env_file:
      - ./.env

  lsp-server:
    build: ./lsp-server
    restart: unless-stopped
