"""Extended HelpdeskTicket with custom methods."""

from typing import Any, Dict
from odoo_records import _HelpdeskTicket
from market_comm_event_log_extended import MarketCommEventLogExtended

class KvStore:
    """Key-value store for Odoo."""

    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def get_many(self, *keys: str) -> tuple[Any, ...]: ...
    def set_many(self, values: Dict[str, Any]) -> None: ...

class HelpdeskTicketExtended(_HelpdeskTicket):
    """HelpdeskTicket with custom business logic methods."""

    market_comm_event_log_ids: MarketCommEventLogExtended
    def kv_store(self) -> KvStore: ...
    def run_code_and_set_result(self) -> Any: ...
    def check_compatibility_matrix(self, **kwargs: Any) -> Any: ...
    def create_matrix_process(self, **kwargs: Any) -> Any: ...
    def sudo(self) -> HelpdeskTicketExtended: ...
