"""Extended HelpdeskTicket with custom methods."""

from typing import Any, Dict, List, Union
from odoo_records import HelpdeskTicket as _HelpdeskTicket


class KvStore:
    """Key-value store for Odoo."""
    def get(self, key: str) -> Any: ...
    def set(self, key: str, value: Any) -> None: ...
    def get_many(self, *keys: str) -> tuple[Any, ...]: ...
    def set_many(self, values: Dict[str, Any]) -> None: ...


class HelpdeskTicket(_HelpdeskTicket):
    """HelpdeskTicket with custom business logic methods."""

    def kv_store(self) -> KvStore: ...
    def run_code_and_set_result(self) -> Any: ...
    def check_compatibility_matrix(self, **kwargs: Any) -> Any: ...
    def create_matrix_process(self, **kwargs: Any) -> Any: ...
