"""Shared Recordset base class for all Odoo models."""

from typing import Any, Dict, List, Optional, Union, Iterator
import datetime as _dt

class Recordset:
    """Base class for all Odoo model record objects."""

    id: int
    ids: List[int]
    create_date: _dt.date
    write_date: _dt.date
    create_uid: "Recordset"
    write_uid: "Recordset"
    def __getattr__(self, name: str) -> Any: ...
    def browse(self, ids: Union[int, List[int]]) -> "Recordset": ...
    def write(self, vals: Dict[str, Any]) -> bool: ...
    def search(
        self,
        domain: List[Any],
        limit: Optional[int] = None,
        order: Optional[str] = None,
        offset: int = 0,
    ) -> "Recordset": ...
    def create(self, vals: Dict[str, Any]) -> "Recordset": ...
    def sudo(self) -> "Recordset": ...
    def with_context(self, ctx: Dict[str, Any] = ..., **kwargs: Any) -> "Recordset": ...
    def filtered(self, func: Any) -> "Recordset": ...
    def mapped(self, field: str) -> Any: ...
    def sorted(self, key: Any = None, reverse: bool = False) -> "Recordset": ...
    def exists(self) -> "Recordset": ...
    def unlink(self) -> bool: ...
    def get_payload(self) -> Any: ...
    def __getitem__(self, key: Union[str, int]) -> Any: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator["Recordset"]: ...
    def __len__(self) -> int: ...
