name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

defaults:
  run:
    working-directory: desktop-app

jobs:
  linux-win:
    runs-on: ubuntu-latest
    container: electronuserland/builder:wine
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run build && npx electron-builder --win nsis --linux AppImage --linux deb --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build && npx electron-builder --mac --publish always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
